AWSTemplateFormatVersion: 2010-09-09
Description: Redis Playground - ElastiCache for Redis cluster

Parameters:
  StackNamePrefix:
    Type: String

Resources:
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: !Sub Security group for ${AWS::StackName}
      GroupName: !Sub ${AWS::StackName}-sg
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId:
            Fn::ImportValue: !Sub ${StackNamePrefix}-ec2-workspace-WorkspaceSecurityGroup
      VpcId: !ImportValue infra-vpc-VpcId
      Tags:
        - { Key: Name, Value: !Sub '${AWS::StackName}-sg' }

  SubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      CacheSubnetGroupName: !Sub ${AWS::StackName}-subnetgroup
      Description: !Sub Subnet Group for ${AWS::StackName} Redis cluster
      SubnetIds:
        - !ImportValue infra-vpc-sn-private-with-endpoints-a
        # - !ImportValue infra-vpc-sn-private-with-endpoints-b

  ParameterGroupRedis60:
    Type: 'AWS::ElastiCache::ParameterGroup'
    Properties:
      Description: !Sub Parameter Group for ${AWS::StackName} Redis cluster
      CacheParameterGroupFamily: redis6.x
      Properties:
        maxmemory-policy: allkeys-lru

  ReplicationGroup:
    Type: AWS::ElastiCache::ReplicationGroup
    Properties:
      AtRestEncryptionEnabled: true
      AutomaticFailoverEnabled: false # only enable if you have multiple clusters
      AutoMinorVersionUpgrade: true
      CacheNodeType: cache.r6g.large
      CacheParameterGroupName: !Ref ParameterGroupRedis60
      CacheSubnetGroupName: !Ref SubnetGroup
      Engine: redis
      EngineVersion: 6.x
      NumNodeGroups: 1
      ReplicasPerNodeGroup: 0
      ReplicationGroupId: !Sub ${AWS::StackName}
      ReplicationGroupDescription: !Sub Redis Cluster ${AWS::StackName}
      SecurityGroupIds:
        - !GetAtt SecurityGroup.GroupId
      SnapshotRetentionLimit: 1
      Tags:
        - { Key: Name, Value: !Sub '${AWS::StackName}' }
      TransitEncryptionEnabled: false

Outputs:
  PrimaryAddress:
    Value: !GetAtt ReplicationGroup.PrimaryEndPoint.Address
  PrimaryPort:
    Value: !GetAtt ReplicationGroup.PrimaryEndPoint.Port
