AWSTemplateFormatVersion: 2010-09-09
Description: Redis Playground - Legacy ElastiCache for Redis cluster for upgrade testing

Parameters:
  StackNamePrefix:
    Type: String

Resources:
  SecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: !Sub Security group for ${AWS::StackName}
      GroupName: !Sub ${AWS::StackName}-sg
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId:
            Fn::ImportValue: !Sub ${StackNamePrefix}-ec2-workspace-WorkspaceSecurityGroup
      VpcId: !ImportValue infra-vpc-VpcId
      Tags:
        - { Key: Name, Value: !Sub '${AWS::StackName}-sg' }

  SubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      CacheSubnetGroupName: !Sub ${AWS::StackName}-subnetgroup
      Description: !Sub Subnet Group for ${AWS::StackName} Redis cluster
      SubnetIds:
        - !ImportValue infra-vpc-sn-private-with-endpoints-a
        # - !ImportValue infra-vpc-sn-private-with-endpoints-b

  ParameterGroupRedis40:
    Type: 'AWS::ElastiCache::ParameterGroup'
    Properties:
      Description: !Sub Parameter Group for ${AWS::StackName} Redis cluster
      CacheParameterGroupFamily: redis4.0
      Properties:
        maxmemory-policy: allkeys-lru
        notify-keyspace-events: KA

  CacheCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      AutoMinorVersionUpgrade: true
      CacheNodeType: cache.r3.large
      CacheParameterGroupName: !Ref ParameterGroupRedis40
      CacheSubnetGroupName: !Ref SubnetGroup
      ClusterName: !Sub ${AWS::StackName}
      Engine: redis
      EngineVersion: 4.0.10
      NumCacheNodes: 1
      SnapshotRetentionLimit: 1
      Tags:
        - { Key: Name, Value: !Sub '${AWS::StackName}' }
      VpcSecurityGroupIds:
        - !GetAtt SecurityGroup.GroupId

Outputs:
  RedisAddress:
    Value: !GetAtt CacheCluster.RedisEndpoint.Address
  RedisPort:
    Value: !GetAtt CacheCluster.RedisEndpoint.Port